version: "3"
services:
  app:
    env_file:
      - .env
    container_name: awesome_nest_boilerplate
    restart: always
    build: .
    ports:
      - "$PORT:$PORT"
    links:
      - postgres
    environment:
      - TZ=Asia/Karachi  # GMT+5 Time Zone

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'Asia/Karachi'  # GMT+5 Time Zone
      PGTZ: 'GMT'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Use a named volume for PostgreSQL data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    env_file:
      - .env
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /Users/hhsadiq/dev/docker_data/pgadmin:/root/.pgadmin # update the path in the docker virtual file sharing as well
    env_file:
      - .env
    links:
      - postgres

volumes:
  postgres_data:  # Define the named volume
    driver: local
